### ISSUE TITLE
N:N Relationship import is not working

### ISSUE THREAD

**Issue by olga-malgina** [MscrmTools/Javista.XrmToolBox.ManageNN#2]
Hi,

I've been trying to import N:N relationship between Users and Security roles, but to no effect.
I choose users to be the first entity, security roles as the second, choose a file in .csv format (witn comma deilimiter) and choose the comma separator in the plugin panel. And nothing happens after that.
I tried semicolon separator - the same story. When there is something wrong in the file or the separators don't match it throws back errors, but when everything is ok, the import just doesn't happen.

The version of the plugin is 1.2016.5.3

Will appreciate your advice. Thanks!

**Comment by MscrmTools** [comment]
@olga-malgina can you explain what data you use to link roles to user, in the mapping file?

**Comment by olga-malgina** [comment]
@MscrmTools Thanks for quick response!
I used a custom field for user - that would be a specially created name field, and for the security roles I used Unique Identifier - already existing attribute - Name.

The name of the user and the name of the security role are correct, as I actually exported them first using the plugin.

**Comment by MscrmTools** [comment]
The problem is (maybe) that there can be multiple roles with the same name (as many as Business units) so Name for the Role entity may not be appropriate
Are you in this situation where there are multiple BU?

**Comment by olga-malgina** [comment]
Indeed, this is a situation with multiple roles with the same names for different BUs.
Another field suggested by the plugin is 'importsequencenumber', though it's empty for all the roles :(
So would you suggest that adding a specific unique identifier might solve the issue?

**Comment by MscrmTools** [comment]
In you case, the only possibility is to use the uniqueidentifier

OR

use the XrmToolBox plugin User Role Manager : it's a manual process but not so complicated

**Comment by olga-malgina** [comment]
Ok, I'll try one of those. Thanks a lot for your help, really appreciate it!

**Comment by MscrmTools** [comment]
It seems the tool did not display error when it occurs. A new version will fix this
