### ISSUE TITLE
Log export

### ISSUE THREAD

**Issue by MikkelMunkholm** [MscrmTools/Javista.XrmToolBox.ManageNN#4]
Hi all,

New to GitHub.

I am using XRM and Manage NN Relationships for work, and have a request/desire for the future.
It would be greate to have the possibility to export the log, this would make error finding a lot easier.

Thanks

**Comment by MscrmTools** [comment]
Hi,
Welcome to Github! 

Yes I know, this is an often requested feature. I will implement it for next release

**Comment by MikkelMunkholm** [comment]
Thanks for the swift reply.
When is the next release scheduled?

**Comment by MscrmTools** [comment]
I don't know, when I'll find time to work on it

That can be tomorrow, in a week or later
