### ISSUE TITLE
Error Principal User {Id=} is missing prvAppend privilige (id=)

### ISSUE THREAD

**Issue by philipshotton** [MscrmTools/Javista.XrmToolBox.ManageNN#8]
Hi

I am using this in D365O version 9 and seem to be getting a few errors now and again...

Some of the imports work and some fail saying that the prvAppend or prvRead is missing - but I am a Sys Admin and surely it should fail for every call?

If I re-run the processing a few more work (that didn't) and then others say that they exist already..  So for the moment I am going to import them until they all 'already exist'.

This is being imported in to our sandbox instance.

Any ideas about the error?

**Comment by MscrmTools** [comment]
Any plugin registered on associate message?

**Comment by philipshotton** [comment]
Hi

I don't think so...  This is a very simple Dynamics instance.  With very little (if any) heavy customisation in it.

**Comment by MscrmTools** [comment]
If errors are random, then I guess this is more due to platform instability

**Comment by philipshotton** [comment]
I agree - but was wondering if you'd used NN with v9.0 Online Sandbox instances.  Just in case there's something that is going wrong or maybe a timing issue?

I'm importing around 1200 NN relationships if that makes any difference.
